### ISSUE TITLE
Invalid input syntax for type timestamp

### ISSUE THREAD

**Issue by mlavruk** [theforeman/smart_proxy_openscap#24]
Hello,
recently I updated smart_proxy_openscap and foreman_openscap  to latest version:
```
[root@foreman]# gem list | grep -e 'foreman\|proxy\|openscap\|scaptimony'
foreman_openscap (0.5.3)
foreman_scap_client (0.1.2, 0.1.1)
hammer_cli_foreman (0.3.0)
openscap (0.4.4)
puppetdb_foreman (0.2.0)
scaptimony (0.3.2)
smart_proxy (1.11.0.develop)
smart_proxy_openscap (0.5.3, 0.4.1)
[root@foreman]# 
```

After this update I got the following issue:
```
D, [2016-02-10T07:15:12.231486 #4667] DEBUG -- : Uploading 339e9bb44fb38bd7eec230b0e567c99f32d9a34823f6a8f319e1d6da85cfd83e to Foreman
D, [2016-02-10T07:15:12.879380 #4667] DEBUG -- : {
  "error": {"message":"PGError: ERROR:  invalid input syntax for type timestamp: \"1455114345\"\nLINE 1: ...icy_id\" = 8 AND \"scaptimony_arf_reports\".\"date\" = '145511434...\n                                                           ^\n: SELECT  \"scaptimony_arf_reports\".* FROM \"scaptimony_arf_reports\"  WHERE \"scaptimony_arf_reports\".\"asset_id\" = 3 AND \"scaptimony_arf_reports\".\"policy_id\" = 8 AND \captimony_arf_reports\".\"date\" = '1455114345' AND \"scaptimony_arf_reports\".\"digest\" = '3427ee4d36dfd69a16275731bfa7054a522e85da447f4cb047fa47842ef55253' ORDER BY scaptimony_arf_reports.created_at DESC LIT 1"}
}

D, [2016-02-10T07:15:12.879747 #4667] DEBUG -- : /usr/share/ruby/net/http/response.rb:119:in `error!'
	/usr/share/ruby/net/http/response.rb:128:in `value'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/foreman_forwarder.rb:11:in `post_arf_report'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:59:in `forward_arf_file'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:51:in `block in forward_date_dir'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:46:in `foreach'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:46:in `forward_date_dir'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:39:in `block in forward_policy_dir'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:35:in `foreach'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:35:in `forward_policy_dir'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:28:in `block in forward_cname_dir'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:24:in `foreach'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:24:in `forward_cname_dir'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:11:in `block in post_arf_from_spool'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:7:in `foreach'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/spool_forwarder.rb:7:in `post_arf_from_spool'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/lib/smart_proxy_openscap/openscap_lib.rb:46:in `send_spool_to_foreman'
	/usr/local/share/gems/gems/smart_proxy_openscap-0.5.3/bin/smart-proxy-openscap-send:39:in `<top (required)>'
	/usr/local/bin/smart-proxy-openscap-send:23:in `load'
	/usr/local/bin/smart-proxy-openscap-send:23:in `<main>'
```

Information from database:
```
foreman=# select * from scaptimony_arf_reports
foreman-# \d+ scaptimony_arf_reports
                                                         Table "public.scaptimony_arf_reports"
   Column   |            Type             |                              Modifiers                              | Storage  | Stats target | Description 
------------+-----------------------------+---------------------------------------------------------------------+----------+--------------+-------------
 id         | integer                     | not null default nextval('scaptimony_arf_reports_id_seq'::regclass) | plain    |              | 
 asset_id   | integer                     |                                                                     | plain    |              | 
 policy_id  | integer                     |                                                                     | plain    |              | 
 date       | timestamp without time zone |                                                                     | plain    |              | 
 digest     | character varying(128)      |                                                                     | extended |              | 
 created_at | timestamp without time zone | not null                                                            | plain    |              | 
 updated_at | timestamp without time zone | not null                                                            | plain    |              | 
Indexes:
    "scaptimony_arf_reports_pkey" PRIMARY KEY, btree (id)
    "index_scaptimony_arf_reports_on_digest" UNIQUE, btree (digest)
    "index_scaptimony_arf_reports_unique_set" UNIQUE, btree (asset_id, policy_id, date, digest)
Has OIDs: no

foreman-#
```

Do you have any idea why this is happening?

**Comment by shlomizadok** [comment]
Yeah, This is happening because foreman_openscap 0.5.3 & smart_proxy_openscap 0.5.3 are supposed to be working **without** Scaptimony engine which is still there.
Please note that 0.5.3 is for Foreman 1.11 (nightly), so maybe you should rollback to version 0.4.3 if you are on older Foreman version.
Hope this helps.

**Comment by mlavruk** [comment]
Yes, thanks for the help.
