### ISSUE TITLE
Exception when trying to upload report

### ISSUE THREAD

**Issue by petems** [theforeman/smart_proxy_openscap#34]
When trying to upload a report with `/usr/bin/foreman_scap_client` I get a weird exception:

```
E, [2016-05-22T15:09:42.258114 #12681] ERROR -- : undefined method `join' for #<String:0x007f43643fcb00> (NoMethodError)
/usr/share/gems/gems/sinatra-1.3.5/lib/sinatra/showexceptions.rb:37:in `rescue in call'
/usr/share/gems/gems/sinatra-1.3.5/lib/sinatra/showexceptions.rb:21:in `call'
/usr/share/gems/gems/sinatra-1.3.5/lib/sinatra/base.rb:124:in `call'
/usr/share/gems/gems/sinatra-1.3.5/lib/sinatra/base.rb:1417:in `block in call'
/usr/share/gems/gems/sinatra-1.3.5/lib/sinatra/base.rb:1499:in `synchronize'
/usr/share/gems/gems/sinatra-1.3.5/lib/sinatra/base.rb:1417:in `call'
/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
/usr/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
/usr/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
/usr/share/gems/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/usr/share/ruby/webrick/httpserver.rb:138:in `service'
/usr/share/ruby/webrick/httpserver.rb:94:in `run'
/usr/share/ruby/webrick/server.rb:295:in `block in start_thread'
```

This is actually a redherring error from Sinatra (https://github.com/sinatra/sinatra/issues/951), upgrading the smart proxy sinatra to newer gives me the actual error:

```
Proxy::OpenSCAP::StoreFailedError at /compliance/arf/5
Could not fulfill request: undefined local variable or method `dir' for #<Proxy::OpenSCAP::StorageFS:0x00000002ac1b40>
file: storage_fs.rb location: rescue in store line: 59
```

**Comment by petems** [comment]
Ok, after some investigation, was missing config settings from `/etc/foreman-proxy/settings.d/openscap.yml`

Adding the following fixes it:
```
:contentdir: /var/lib/openscap/content
:reportsdir: /usr/share/foreman-proxy/openscap/content
```

Would be good to:

1. Catch and throw error when these are not set, as the actual error is pretty hard to see
2. Make sure the foreman-installer actually sets these settings:

**Comment by ares** [comment]
Thanks for the detailed report and solution, could you please report it in our [issue tracker](http://projects.theforeman.org/projects/smart-proxy-openscap)? You can use github account there as well.

**Comment by petems** [comment]
Done! 👍  http://projects.theforeman.org/issues/15222

**Comment by ares** [comment]
Thank you! :clap:
